const CONFIG = {
  DEFAULT_HEIGHT: 1080,
  DEFAULT_WIDTH: 1920,
  DEFAULT_GRAVITY: 200,
  CARD_WIDTH: 224,
  HAND_DEPTH: 3,
  HAND_ORBITAL: 1200,
  DRAWS_PER_ROUND: 4
}

export default CONFIG
